{
  "comments": [
    {
      "key": {
        "uuid": "5ad0253b_2f6da204",
        "filename": "openstack-ironic-python-agent.spec",
        "patchSetId": 2
      },
      "lineNbr": 116,
      "author": {
        "id": 403
      },
      "writtenOn": "2019-01-28T06:22:50Z",
      "side": 1,
      "message": "what about Fedora? is the issue not there? From bugzilla it seems it affected there as well.",
      "range": {
        "startLine": 116,
        "startChar": 2,
        "endLine": 116,
        "endChar": 7
      },
      "revId": "1cb05a311b18c880565508134744bc83f439dcea",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}